name: Create the DEB

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  Create_Packages:
    name: Create Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "REPO"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libsfml-dev libsdl2-dev libsdl2-mixer-2.0-0 mesa-utils freeglut3-dev tcl build-essential

      - name: Build Extreme Tux Racer
        run: |
          cd REPO
          mkdir -p extremetuxracer_0.8.4-1/usr
          cp -r DEBIAN extremetuxracer_0.8.4-1/DEBIAN
          ./configure
          make
          make install prefix=extremetuxracer_0.8.4-1/usr
          cd ..
          

      - name: Copy script files around to stop .github from being added to the package then build the package
        run: |
          cp -Rf REPO/extremetuxracer_0.8.4-1/usr REPO/extremetuxracer_0.8.4-1/DEBIAN PKG_SOURCE
          dpkg-deb --build PKG_SOURCE extremetuxracer.deb

      - name: Release the Package
        uses: softprops/action-gh-release@v1
        with:
          files: extremetuxracer.deb
